name = "voice-chatbot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[durable_objects]]
binding = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[ai]
binding = "AI"